/*
 * Greeter
 * This is an example of a simplistic OpenAPI document.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.example.greeter;

import org.example.ApiClient;
import org.example.ApiException;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.HashMap;

/**
 * API tests for GreeterApi
 */
public class GreeterApiTest {

    /**
     * Greeting service.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void greetTest() throws ApiException {
        ApiClient client = new ApiClient();
        HashMap<String,String> variables = new HashMap<>();
        variables.put("host", "http://localhost:8080");
        client.setServerVariables(variables);

        GreeterApi greeter = new GreeterApi(client);
        
        String whom = "Bob";
        String response = greeter.greet(whom);

        assertEquals("Hello, Bob!", response);
    }

}
